# Generated by Django 3.2.6 on 2021-08-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('campaign_id', models.BigIntegerField()),
                ('publisher_id', models.CharField(blank=True, max_length=50, null=True)),
                ('product_id', models.CharField(max_length=30, unique=True)),
                ('murchant', models.CharField(max_length=50, null=True)),
                ('shopper_id', models.CharField(blank=True, max_length=250, null=True)),
                ('hashed_ip', models.CharField(blank=True, max_length=214, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('aff_source', models.CharField(blank=True, max_length=50, null=True)),
                ('aff_medium', models.CharField(blank=True, max_length=50, null=True)),
                ('aff_term', models.CharField(blank=True, max_length=30, null=True)),
                ('aff_campaign', models.CharField(blank=True, max_length=30, null=True)),
                ('aff_content', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_org', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
