# Generated by Django 3.2.6 on 2021-08-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopper',
            old_name='murchant',
            new_name='merchant',
        ),
    ]
