# Generated by Django 3.2.6 on 2021-08-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_murchant_shopper_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='aff_campaign',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='aff_content',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='aff_medium',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='aff_source',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='aff_term',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='hashed_ip',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='parent_org',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='user_agent',
        ),
    ]
